### ISSUE TITLE
Create research folders

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/guides#150]
### Overview
We need to create Google Drive folders for research so that we have a place to put research documents when they are created.

### Action Items
- [ ] Create the following folders and subfolders inside the `1. Research` folder
   - [ ] 1. Research by Participant Type
   - [ ] 2. Research by Plan # and name
   - [ ] 3. Research Presentations (add shortcuts to presentations from RP folders
   - [ ] Guides and How-Tos
   - [ ] Personas and User Stories and Journeys
   - [ ] Research Current (shortcuts)
   - [ ] Research Templates
      - [ ] Training Materials
      - [ ] Consent Document Templates
- [ ] Add the links to the folders to the wiki

### Resources/Instructions
- wiki: https://github.com/hackforla/guides/wiki/Google-Drive,-Research-Folder
- Google drive: Hack for LA Guides > Hack for LA Guides > GUIDES TEAM FOLDER > [1. Research](https://drive.google.com/drive/folders/1XaL0dUgKzd8P1LZv3RVniQ3SX9UaP3MN)

**Comment by jianwangcat** [comment]
### Overview
We need to create Google Drive folders for research so that we have a place to put research documents when they are created.

### Action Items
- [ ] Create the following folders and subfolders inside the `1. Research` folder
   - [ ] 1. Research by Participant Type
   - [ ] 2. Research by Plan # and name
   - [ ] 3. Research Presentations (add shortcuts to presentations from RP folders
   - [ ] Guides and How-Tos
   - [ ] Personas and User Stories and Journeys
   - [ ] Research Current (shortcuts)
   - [ ] Research Templates
      - [ ] Training Materials
      - [ ] Consent Document Templates
- [ ] Add the links to the folders to the wiki

### Resources/Instructions
- wiki: https://github.com/hackforla/guides/wiki/Google-Drive,-Research-Folder
- Google drive: Hack for LA Guides > Hack for LA Guides > GUIDES TEAM FOLDER > [1. Research](https://drive.google.com/drive/folders/1XaL0dUgKzd8P1LZv3RVniQ3SX9UaP3MN)

**Comment by jianwangcat** [comment]
### Overview
Finished the Action Items

### Action Items
- [x] Create the following folders and subfolders inside the `1. Research` folder
   - [x] 1. Research by Participant Type
   - [x] 2. Research by Plan # and name
   - [x] 3. Research Presentations (add shortcuts to presentations from RP folders
   - [x] Guides and How-Tos
   - [x] Personas and User Stories and Journeys
   - [x] Research Current (shortcuts)
   - [x] Research Templates
      - [x] Training Materials
      - [x] Consent Document Templates
- [x] Add the links to the folders to the wiki

### Resources/Instructions
- wiki: https://github.com/hackforla/guides/wiki/Google-Drive,-Research-Folder
- Google drive: Hack for LA Guides > Hack for LA Guides > GUIDES TEAM FOLDER > [1. Research](https://drive.google.com/drive/folders/1XaL0dUgKzd8P1LZv3RVniQ3SX9UaP3MN)
