### ISSUE TITLE
Create a ReadMe

### ISSUE THREAD

**Issue by SheIsBukki** [hackforla/guides#6]
### Dependency
~#8~

### Overview
We need to have a working READme file to easily onboard new team members and compile relevant information for other teams  and CoPs that will interact with us.

### Action Items
- [x] Review the readme file and identify what information is needed and applicable
- [x] Review GreenEarthOS repo as a guide
- [ ] Review the project one sheet and other documentation to be used in creating content
- [ ] Update project one sheet #8 
- [x] Apply changes to ReadMe

### Resources/Instructions
https://github.com/hackforla/guides/blob/main/README.md
[Green Earth OS](https://github.com/hackforla/GreenEarthOS)

**Comment by SheIsBukki** [comment]
I think we don't need Installation Instructions, Working with forks and branches, Working with pull requests and reviews, and Testing. Licensing too maybe
I don't know whether PM also have to work on Issues; bugs, features, in the same way engineering team does.

**Comment by ExperimentsInHonesty** [comment]
### Hack for LA Guides
The Guides project seeks to create guides out of the effective practices that we have created/iterated on projects in order to share replicable processes and practices so that we can continue to grow our peer learning and iterative culture,  improving outcomes for the whole ecosystem.

**Comment by ExperimentsInHonesty** [comment]
[our logo here]

### Hack for LA Guides
The Guides project seeks to create guides out of the effective practices that we have created/iterated on projects in order to share replicable processes and practices so that we can continue to grow our peer learning and iterative culture,  improving outcomes for the whole ecosystem.

### Project context

View the [insert one sheet here]


### Technology used

- [GitHub project board]
- [Slack]
- [Google drive]

# How to contribute

- [Join the HackforLA slack workspace](https://hackforla.org/slack)
- Join the slack channel [#guides] and say hi! Tell us what your skillset is and how you're looking to contribute.
- One of our product managers will add you to the meeting invite & the project resources
- Join our team meetings - [insert details about times]
