### ISSUE TITLE
Recruit UX Research

### ISSUE THREAD

**Issue by carolzjy** [hackforla/guides#76]
### Overview
We need to recruit a UX research member to help us understand how to improve guides' workshop and slide deck.

### Action Items

- [x] Create a UX research role descriptions & responsibilities 
- [x] Get Bonnie's approval on the descriptions
- [x] Post the information in the "[UI/UX Research Open Roles](https://github.com/hackforla/UI-UX/projects/2#card-53063726)" page
- [x] Reach out to members on the UI/UX slack channel

### Resources/Instructions
[Research plan issue ](#75 )
[UX Research Recruitment Descriptions DRAFT](https://docs.google.com/document/d/1vLFX7qq2mh_hz1HXDxFK-Bid_TMNQ0Wiuj8yjrcgWm0/edit)

**Comment by carolzjy** [comment]
@ExperimentsInHonesty Hi Bonnie, I created a [draft](https://docs.google.com/document/d/1vLFX7qq2mh_hz1HXDxFK-Bid_TMNQ0Wiuj8yjrcgWm0/edit) for the UX research recruitment. Let me know if you have any feedback. Thanks!

**Comment by ExperimentsInHonesty** [comment]
**Project Name**: HfLA Guides

**Volunteer Opportunity**: 
We are looking for a UI/UX researcher who can collaborate with the Guides team and produce insights to help the team understand how to best deliver the guides' workshop so that we can make improvements to the slide deck. In the process, the UX researcher would conduct research on CoP attendants’ sentiments and feedback before and after the presentation. 

**Duration**: Temporary (in the next several weeks)

**Who to communicate your interest to**
- Slack channel link: #guides
- Slack name of person to contact in the channel -  Bukki or Carol Zhu

**When we meet**
Mondays, Wednesdays, Fridays @ 7:30 am PDT

[Read more about the project](https://www.hackforla.org/projects/guides-team)

**Comment by edwardsarah** [comment]
![image](https://user-images.githubusercontent.com/64277558/224377226-53e75fc1-cc01-48f3-b8cc-5d312acd1dbe.png)

Project Name: HfLA Guides

Volunteer Opportunity:
We are looking for a Lead UX researcher who can collaborate with the Guides team and produce insights to help the team understand how to best deliver the guides' workshops. In the first few weeks, the UX Research Lead would set up the wiki structure and create a research road map for understanding how new guide contributors move through the gather examples phase. 

Duration: Ongoing

Who to communicate your interest to

Slack channel link: [#guides] (https://app.slack.com/client/T04502KQX/C028T9XU9S5)
Slack name of person to contact in the channel - Sarah Edwards
When we meet
Fridays @ 7:30 am PDT

[Read more about the project](https://www.hackforla.org/projects/guides-team)

**Comment by edwardsarah** [comment]
Reached out to UI-UX CoP leads and they said @ExperimentsInHonesty can come to the next CoP meeting to talk about what the Guides team is looking for. Need to know what time to expect her.

<img width="601" alt="Screen Shot 2023-04-18 at 11 21 40 AM" src="https://user-images.githubusercontent.com/64277558/232748553-a9eed5c1-ab62-4d6c-b185-3055393c064d.png">

**Comment by edwardsarah** [comment]
Recruited Rhoda to the project as our UX research lead
